### ISSUE TITLE
About single modality feature extractor

### ISSUE THREAD

**Issue by EricKani** [PingCheng-Wei/DepressionEstimation#1]
Hi PingCheng,

This is a great project with good code structure and writing habit! It's easy to follow.
I found two question here:
1) I found there only has an end-to-end training pipeline, without single-modality feature extractor pre-training code. 
If I want to implement this framework to my own dataset, how should I train my own feature extractor? Only replace concatenated feature with single-modality feature, then sent it to the same evaluator?
2) Will you open-source your three pre-trained feature extractor?

Best,
Eric

**Comment by PingCheng-Wei** [comment]
Hi Eric,

Thank you very much! I am glad that this project can help you.

For your questions:
1. We trained our single-modal model (feature extractor) separately from the multi-modal one. For single-modal models, you can find them in models/(Audio, Visual, Text)_ConvLSTM folders and look at how we trained feature extractors of a single-modal model. I am not sure what your dataset looks like, but I guess it's single-modal. In this case, if you want to train the single-modal feature extractor, you only need the feature extractor itself plus an evaluator layer (as output head) and make sure the output of the feature extractor matches the input dimension requirement of the evaluator. You don't really need concatenation and sub-attention fusion layers in this case. However, If you still want to implement the framework of a multi-modal model, including feature extractors, sub-attentional fusion layer, and evaluator, but for single-modality, you could also just train the whole model together from scratch. In this case, you just need to make sure the output dim of the previous block matches the input dim of the next block. 
2. Yes, I can do that. I will share the link to the weights of pre-trained feature extractors in the Readme in the near future. 


Best,

Ping-Cheng

**Comment by EricKani** [comment]
Hi Ping-Cheng,

Thanks for your response!
1. I get it. I find in your single-modality extractor training code, you exclude attention module, while in sub-attention folder, you include attention module in evaluator~
2. Thanks! Hoping for that~

Best,
Eric

**Comment by BaiMeiyingxue** [comment]
Hi,
thanks for your effort!
I get the pre-trained file
![pt文件](https://user-images.githubusercontent.com/53547009/221784085-60cf93ef-ef98-4906-b367-18de633bca9a.png)
and I was wondering if I could use the .pt file as pre-trained feature extractors of a single-modal model(Audio, Text_ConvLSTM) to extract features of my own dataset?
Looking forward to your reply!

**Comment by PingCheng-Wei** [comment]
Yes, you can. The model is built based on each functional block and combined together. Hence the weights in the pre-trained file are also stored in a block manner, meaning that you can load particular pre-trained weights of particular functional blocks by calling the corresponding key, like a dictionary variable. Take a look at the "[get_models](https://github.com/PingCheng-Wei/DepressionEstimation/blob/main/models/AVT_ConvLSTM_Sub-Attention/utils.py#L146)" function in [utils](https://github.com/PingCheng-Wei/DepressionEstimation/blob/main/models/AVT_ConvLSTM_Sub-Attention/utils.py) and see how the model weights are loaded. But you probably have to be aware of the input dimension to the model (pre-trained weights) with your own dataset.

**Comment by BaiMeiyingxue** [comment]
Hi PingCheng-Wei,

Thanks for your response!
I get the input dimension to the audio and text model (pre-trained weights),
![audio_text_net](https://user-images.githubusercontent.com/53547009/222017528-aa19e5c0-b21a-4733-828d-a40376ef0c5e.png)
and I will give try to load the corresponding pre-trained weights.

**Comment by BaiMeiyingxue** [comment]
Hi , 
I'm coming back again~
I encountered this error when running text_net.load() function,


Traceback (most recent call last):
  File "test_get_model.py", line 33, in <module>
    audio_net,text_net = utils.get_models(model_config,args)
  File "/home/qianslab/zhanghaoplus/fight_for_save/AVT_ConvLSTM_Sub-Attention/utils.py", line 295, in get_models
    text_net.load_state_dict(new_state_dict)
  File "/home/qianslab/anaconda3/envs/cuda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Unexpected key(s) in state_dict: "module.lstm.weight_ih_l2", "module.lstm.weight_hh_l2", "module.lstm.bias_ih_l2", "module.lstm.bias_hh_l2", "module.lstm.weight_ih_l2_reverse", "module.lstm.weight_hh_l2_reverse", "module.lstm.bias_ih_l2_reverse", "module.lstm.bias_hh_l2_reverse", "module.lstm.weight_ih_l3", "module.lstm.weight_hh_l3", "module.lstm.bias_ih_l3", "module.lstm.bias_hh_l3", "module.lstm.weight_ih_l3_reverse", "module.lstm.weight_hh_l3_reverse", "module.lstm.bias_ih_l3_reverse", "module.lstm.bias_hh_l3_reverse".

i print the params in the model and checkpoints:

checkpoints params: conv.conv1.weight
checkpoints params: conv.conv1.bias
checkpoints params: conv.bn1.weight
checkpoints params: conv.bn1.bias
checkpoints params: conv.bn1.running_mean
checkpoints params: conv.bn1.running_var
checkpoints params: conv.bn1.num_batches_tracked
checkpoints params: lstm.weight_ih_l0
checkpoints params: lstm.weight_hh_l0
checkpoints params: lstm.bias_ih_l0
checkpoints params: lstm.bias_hh_l0
checkpoints params: lstm.weight_ih_l0_reverse
checkpoints params: lstm.weight_hh_l0_reverse
checkpoints params: lstm.bias_ih_l0_reverse
checkpoints params: lstm.bias_hh_l0_reverse
checkpoints params: lstm.weight_ih_l1
checkpoints params: lstm.weight_hh_l1
checkpoints params: lstm.bias_ih_l1
checkpoints params: lstm.bias_hh_l1
checkpoints params: lstm.weight_ih_l1_reverse
checkpoints params: lstm.weight_hh_l1_reverse
checkpoints params: lstm.bias_ih_l1_reverse
checkpoints params: lstm.bias_hh_l1_reverse
checkpoints params: fc.fc.weight
checkpoints params: fc.fc.bias
checkpoints params: fc.bnf.weight
checkpoints params: fc.bnf.bias
checkpoints params: fc.bnf.running_mean
checkpoints params: fc.bnf.running_var
checkpoints params: fc.bnf.num_batches_tracked

text model params: module.conv.conv1.weight
text model params: module.conv.conv1.bias
text model params: module.conv.bn1.weight
text model params: module.conv.bn1.bias
text model params: module.conv.bn1.running_mean
text model params: module.conv.bn1.running_var
text model params: module.conv.bn1.num_batches_tracked
text model params: module.lstm.weight_ih_l0
text model params: module.lstm.weight_hh_l0
text model params: module.lstm.bias_ih_l0
text model params: module.lstm.bias_hh_l0
text model params: module.lstm.weight_ih_l0_reverse
text model params: module.lstm.weight_hh_l0_reverse
text model params: module.lstm.bias_ih_l0_reverse
text model params: module.lstm.bias_hh_l0_reverse
text model params: module.lstm.weight_ih_l1
text model params: module.lstm.weight_hh_l1
text model params: module.lstm.bias_ih_l1
text model params: module.lstm.bias_hh_l1
text model params: module.lstm.weight_ih_l1_reverse
text model params: module.lstm.weight_hh_l1_reverse
text model params: module.lstm.bias_ih_l1_reverse
text model params: module.lstm.bias_hh_l1_reverse
text model params: module.fc.fc.weight
text model params: module.fc.fc.bias
text model params: module.fc.bnf.weight
text model params: module.fc.bnf.bias
text model params: module.fc.bnf.running_mean
text model params: module.fc.bnf.running_var
text model params: module.fc.bnf.num_batches_tracked

I don't know how the error happened and where are the unexpected keys in state_dict("module.lstm.weight_ih_l2", "module.lstm.weight_hh_l2", "module.lstm.bias_ih_l2", "module.lstm.bias_hh_l2", "module.lstm.weight_ih_l2_reverse", "module.lstm.weight_hh_l2_reverse", "module.lstm.bias_ih_l2_reverse", "module.lstm.bias_hh_l2_reverse", "module.lstm.weight_ih_l3", "module.lstm.weight_hh_l3", "module.lstm.bias_ih_l3", "module.lstm.bias_hh_l3", "module.lstm.weight_ih_l3_reverse", "module.lstm.weight_hh_l3_reverse", "module.lstm.bias_ih_l3_reverse", "module.lstm.bias_hh_l3_reverse"), could you give me some advice? 


Thanks a lot!

**Comment by BaiMeiyingxue** [comment]
> 
I have solved the problem~

**Comment by BaiMeiyingxue** [comment]
Hi ,
Thanks for your effort! This is a great project with a good code structure! But I have trouble understanding the logic of the preprocessing of the audio [data,](https://github.com/PingCheng-Wei/DepressionEstimation/blob/main/daic_woz_preprocessing/database_generation_v1/database_generation_train.py) 
I have read the article in ReadMe, and I will appreciate it if you can give me more articles and information to  comprehend the 
details of data format or how to create the dataset?
Best wishes, 
BaiMeiyingxue

**Comment by PingCheng-Wei** [comment]
Hi,

You can find more details about the depression dataset generation inside this [document](https://github.com/PingCheng-Wei/DepressionEstimation/blob/main/daic_woz_preprocessing/Chapter3_DepressionDataset.pdf) I wrote, which can also be found under "daic_woz_preprocessing/Chapter3_DepressionDataset.pdf". It should contain everything you need to know and that I have done for the depression dataset generation.

**Comment by BaiMeiyingxue** [comment]
Thank you! Have a nice day!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ping-Cheng ***@***.***&gt;; 
发送时间: 2023年3月13日(星期一) 中午1:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PingCheng-Wei/DepressionEstimation] About single modality feature extractor (Issue #1)





 
Hi,
 
You can find more details about the depression dataset generation inside this document I wrote, which can also be found under "daic_woz_preprocessing/Chapter3_DepressionDataset.pdf". It should contain everything you need to know and that I have done for the depression dataset generation.

**Comment by BaiMeiyingxue** [comment]
By the way, could I get the full article to learn more about the work?&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PingCheng-Wei/DepressionEstimation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 中午1:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PingCheng-Wei/DepressionEstimation] About single modality feature extractor (Issue #1)





 
Hi,
 
You can find more details about the depression dataset generation inside this document I wrote, which can also be found under "daic_woz_preprocessing/Chapter3_DepressionDataset.pdf". It should contain everything you need to know and that I have done for the depression dataset generation.

**Comment by PingCheng-Wei** [comment]
Thanks. But unfortunately, I didn't really complete the other chapters at that time because it was not necessary for me at the end.  Chapter 3 is the one that's somewhat completed. If you have some questions, feel free to just ask.

**Comment by BaiMeiyingxue** [comment]
> Thanks. But unfortunately, I didn't really complete the other chapters at that time because it was not necessary for me at the end. Chapter 3 is the one that's somewhat completed. If you have some questions, feel free to just ask.

Got it, thank you!
