### ISSUE TITLE
Why the extractor of text modality is commented out

### ISSUE THREAD

**Issue by EricKani** [PingCheng-Wei/DepressionEstimation#2]
https://github.com/PingCheng-Wei/DepressionEstimation/blob/7c796acf3e9aa8c7407455b548d9a08dc55bfd4d/models/AVT_ConvLSTM_Sub-Attention/main_phq-subscores.py#L65

**Comment by PingCheng-Wei** [comment]
Oh sorry, I forget to change it back. I uploaded the wrong one that I tried to play around with and see the different effects. It should not be commented out actually! But the rest should be correct. Thanks for the issue. I will fix it right now.
