### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by zoeshao0425** [PingCheng-Wei/DepressionEstimation#7]
Hi, I was looking for your pre-trained weights but it seems that they are not available in the google drive link you provided. Could you please check this? Thanks!

**Comment by PingCheng-Wei** [comment]
Hi, sorry about that. I have just updated the link. Can you please help me double-check the link? Thanks

**Comment by zoeshao0425** [comment]
The link works perfectly right now. Thanks for updating!
