### ISSUE TITLE
Correspondence between paper (Multi-modal Depression Estimation based on Sub-attentional Fusion) and codes

### ISSUE THREAD

**Issue by BaiMeiyingxue** [PingCheng-Wei/DepressionEstimation#8]
Hi PingCheng-Wei,
      Is there relevant code about the implementation of the content _Sensitivity of Participants Depression Estimation. To further allay the concern regarding the representation of our models since the depression of a participant in GT is diagnosed by the specialist based on a whole interview instead of a clip, the participant analysis is conducted by recombining the clips as well as the predicted scores back into each participant to form the original interview._ 
   Thank you!

**Comment by PingCheng-Wei** [comment]
Hi,

You can find the code implementation for both analyses, i.e. gender-level or participant-level, in the `main_inference.py` file in each model. For example, you can find this part in [AVT_ConvLSTM_Sub-Attention](https://github.com/PingCheng-Wei/DepressionEstimation/tree/main/models/AVT_ConvLSTM_Sub-Attention) model, starting from [line 260](https://github.com/PingCheng-Wei/DepressionEstimation/blob/main/models/AVT_ConvLSTM_Sub-Attention/main_inference.py#L260).

**Comment by BaiMeiyingxue** [comment]
I got it! Thanks for your reply!
